/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahospitalmanagment;

import actors.consultant;
import connections.consultantConnect;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinithi
 */
public class addConsultant extends javax.swing.JFrame {

    /**
     * Creates new form addConsultant
     */
    public addConsultant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelSpecialization = new javax.swing.JLabel();
        jLabelCharges = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSpecialization = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldCharges = new javax.swing.JTextField();
        jButtonSubmit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Add Consultant");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabelName.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(0, 51, 153));
        jLabelName.setText("Name");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabelGender.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(0, 51, 153));
        jLabelGender.setText("Gender");
        jPanel1.add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabelSpecialization.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabelSpecialization.setForeground(new java.awt.Color(0, 51, 153));
        jLabelSpecialization.setText("Specialization");
        jPanel1.add(jLabelSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabelCharges.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabelCharges.setForeground(new java.awt.Color(0, 51, 153));
        jLabelCharges.setText("Charges (for 1 hour)");
        jPanel1.add(jLabelCharges, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 230, -1));
        jPanel1.add(jTextFieldSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 230, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 0, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));
        jPanel1.add(jTextFieldCharges, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 230, -1));

        jButtonSubmit.setBackground(new java.awt.Color(51, 0, 102));
        jButtonSubmit.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonSubmit.setForeground(new java.awt.Color(204, 204, 204));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jButtonCancel.setBackground(new java.awt.Color(51, 0, 102));
        jButtonCancel.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addDoctorImg.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 420, 370));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        String gender = (String) jComboBox1.getSelectedItem();
        String specialization = jTextFieldSpecialization.getText();
        String chargesText = jTextFieldCharges.getText();

    // Validate input fields
    if (name.isEmpty() || gender == null || specialization.isEmpty() || chargesText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!name.matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(this, "Invalid name! Name should contain only letters and spaces.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    
    
    double charges;
    try {
        charges = Double.parseDouble(chargesText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid charges! Please enter a numeric value.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    consultantConnect ConsultantConnect = new consultantConnect();
    // Create a consultant object
    consultant newConsultant = new consultant(name, gender, specialization, charges);

    // Save the consultant
    boolean isSaved = ConsultantConnect.saveConsultant(newConsultant);

    // Show success or error message
    if (isSaved) {
        JOptionPane.showMessageDialog(this, "Consultant added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        // Optionally, clear the input fields after saving
        jTextFieldName.setText("");
        jTextFieldSpecialization.setText(""); 
        jTextFieldCharges.setText("");
        jComboBox1.setSelectedIndex(0);
        
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add consultant", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addConsultant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addConsultant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addConsultant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addConsultant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addConsultant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCharges;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSpecialization;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldCharges;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSpecialization;
    // End of variables declaration//GEN-END:variables
}
