/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahospitalmanagment;

/**
 *
 * @author Dinithi
 */
public class cashierDashboard extends javax.swing.JFrame {

    /**
     * Creates new form cashierDashboard
     */
    public cashierDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddConsultant = new javax.swing.JButton();
        jButtonAddPatient = new javax.swing.JButton();
        jButtonConsultant = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonAppoinments = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Welcome to Cashier Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonAddConsultant.setBackground(new java.awt.Color(51, 0, 102));
        jButtonAddConsultant.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonAddConsultant.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAddConsultant.setText("Add Consultants");
        jButtonAddConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddConsultantActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, -1));

        jButtonAddPatient.setBackground(new java.awt.Color(51, 0, 102));
        jButtonAddPatient.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonAddPatient.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAddPatient.setText("Add Patient");
        jButtonAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPatientActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, -1));

        jButtonConsultant.setBackground(new java.awt.Color(51, 0, 102));
        jButtonConsultant.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonConsultant.setForeground(new java.awt.Color(204, 204, 204));
        jButtonConsultant.setText("View Consultants");
        jButtonConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultantActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        jButtonLogOut.setBackground(new java.awt.Color(0, 51, 102));
        jButtonLogOut.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(204, 204, 204));
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 273, -1, 40));

        jButtonAppoinments.setBackground(new java.awt.Color(51, 0, 102));
        jButtonAppoinments.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonAppoinments.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAppoinments.setText("Booking Details");
        jButtonAppoinments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppoinmentsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAppoinments, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashierDashboardImg.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddConsultantActionPerformed
        // TODO add your handling code here:
        addConsultant addConsultantView = new addConsultant();
        addConsultantView.setVisible(true);
    }//GEN-LAST:event_jButtonAddConsultantActionPerformed

    private void jButtonAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPatientActionPerformed
        // TODO add your handling code here:
        addPatient addPatientView = new addPatient();
        addPatientView.setVisible(true);
    }//GEN-LAST:event_jButtonAddPatientActionPerformed

    private void jButtonConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultantActionPerformed
        // TODO add your handling code here:
        consultantView ConsultantView = new consultantView();
        ConsultantView.setVisible(true);
    }//GEN-LAST:event_jButtonConsultantActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonAppoinmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppoinmentsActionPerformed
        // TODO add your handling code here:
        patientView PatientView = new patientView();
        PatientView.setVisible(true);
    }//GEN-LAST:event_jButtonAppoinmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashierDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddConsultant;
    private javax.swing.JButton jButtonAddPatient;
    private javax.swing.JButton jButtonAppoinments;
    private javax.swing.JButton jButtonConsultant;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
