/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahospitalmanagment;

/**
 *
 * @author Dinithi
 */
public class managerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form managerDashboard
     */
    public managerDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAddConsultant = new javax.swing.JButton();
        jButtonAddPatient = new javax.swing.JButton();
        jButtonViewConsultant = new javax.swing.JButton();
        jButtonCreateUser = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonAppoinment = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonViewUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 241, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Welcome ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("to the City Nursing Home");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Manager Dashboard");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jButtonAddConsultant.setBackground(new java.awt.Color(102, 0, 102));
        jButtonAddConsultant.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonAddConsultant.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAddConsultant.setText("Add Consultant");
        jButtonAddConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddConsultantActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, 33));

        jButtonAddPatient.setBackground(new java.awt.Color(102, 0, 102));
        jButtonAddPatient.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonAddPatient.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAddPatient.setText("Add Patient");
        jButtonAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPatientActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 160, 33));

        jButtonViewConsultant.setBackground(new java.awt.Color(102, 0, 102));
        jButtonViewConsultant.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonViewConsultant.setForeground(new java.awt.Color(204, 204, 204));
        jButtonViewConsultant.setText("View Consultants");
        jButtonViewConsultant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewConsultantActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonViewConsultant, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 160, 33));

        jButtonCreateUser.setBackground(new java.awt.Color(102, 0, 102));
        jButtonCreateUser.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonCreateUser.setForeground(new java.awt.Color(204, 204, 204));
        jButtonCreateUser.setText("Create User ");
        jButtonCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 160, 35));

        jButtonLogOut.setBackground(new java.awt.Color(102, 0, 102));
        jButtonLogOut.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(204, 204, 255));
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jButtonAppoinment.setBackground(new java.awt.Color(102, 0, 102));
        jButtonAppoinment.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonAppoinment.setForeground(new java.awt.Color(204, 204, 204));
        jButtonAppoinment.setText("Booking Details");
        jButtonAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppoinmentActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAppoinment, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 160, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinithi\\Documents\\NetBeansProjects\\AHospitalManagment\\src\\cashierDashboardImg.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -50, 370, 340));

        jButtonViewUser.setBackground(new java.awt.Color(102, 0, 102));
        jButtonViewUser.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButtonViewUser.setForeground(new java.awt.Color(204, 204, 204));
        jButtonViewUser.setText("View User");
        jButtonViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonViewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddConsultantActionPerformed
        // TODO add your handling code here:
        addConsultant AddConsultantView = new addConsultant();
        AddConsultantView.setVisible(true);
    }//GEN-LAST:event_jButtonAddConsultantActionPerformed

    private void jButtonAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPatientActionPerformed
        // TODO add your handling code here:
        addPatient patientView = new addPatient();
        patientView.setVisible(true); 
    }//GEN-LAST:event_jButtonAddPatientActionPerformed

    private void jButtonViewConsultantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewConsultantActionPerformed
        // TODO add your handling code here:
        consultantView ConsultantView = new consultantView();
        ConsultantView.setVisible(true);
    }//GEN-LAST:event_jButtonViewConsultantActionPerformed

    private void jButtonCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateUserActionPerformed
        // TODO add your handling code here:
        createUser addUserView = new createUser();
        addUserView.setVisible(true);
    }//GEN-LAST:event_jButtonCreateUserActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppoinmentActionPerformed
        // TODO add your handling code here:
        patientView PatientView = new patientView();
        PatientView.setVisible(true);
    }//GEN-LAST:event_jButtonAppoinmentActionPerformed

    private void jButtonViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewUserActionPerformed
        // TODO add your handling code here:
        userView UserView = new userView();
        UserView.setVisible(true);
    }//GEN-LAST:event_jButtonViewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddConsultant;
    private javax.swing.JButton jButtonAddPatient;
    private javax.swing.JButton jButtonAppoinment;
    private javax.swing.JButton jButtonCreateUser;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonViewConsultant;
    private javax.swing.JButton jButtonViewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
